sample	coverage	taxonomy
2_component_0.1	7.66	Root; d__Viruses; p__Uroviricota; c__Caudoviricetes; o__novel_order_237_of_Caudoviricetes; f__novel_family_172_of_novel_order_237_of_Caudoviricetes; g__novel_genus_0_of_novel_subfamily_8_of_novel_family_172_of_novel_order_237_of_Caudoviricetes; s__Vibrio_phage_vB_VpP_BT-1011
