sample	coverage	taxonomy
2_component_79.1	6.91	Root; d__Viruses; p__Uroviricota; c__Caudoviricetes; o__novel_order_48_of_Caudoviricetes; f__novel_family_16_of_novel_order_48_of_Caudoviricetes; g__Pahexavirus; s__Propionibacterium_phage_PAC1
