sample	coverage	taxonomy
2_component_15.1	0.04	Root; d__Viruses; p__Uroviricota; c__Caudoviricetes; o__novel_order_237_of_Caudoviricetes; f__novel_family_193_of_novel_order_237_of_Caudoviricetes; g__Jedunavirus
2_component_15.1	7.9	Root; d__Viruses; p__Uroviricota; c__Caudoviricetes; o__novel_order_237_of_Caudoviricetes; f__novel_family_193_of_novel_order_237_of_Caudoviricetes; g__Jedunavirus; s__Klebsiella_phage_vB_KpnM_15-38_KLPPOU148
