sample	coverage	taxonomy
2_component_19.1	7.56	Root; d__Viruses; p__Uroviricota; c__Caudoviricetes; o__novel_order_123_of_Caudoviricetes; f__novel_family_56_of_novel_order_123_of_Caudoviricetes; g__Lenusvirus; s__Lenusvirus_nyseid
