sample	coverage	taxonomy
2_component_72.1	9.75	Root; d__Viruses; p__Uroviricota; c__Caudoviricetes; o__novel_order_79_of_Caudoviricetes; f__novel_family_29_of_novel_order_79_of_Caudoviricetes; g__novel_genus_5_of_novel_subfamily_1_of_novel_family_29_of_novel_order_79_of_Caudoviricetes; s__Enterococcus_phage_phiEf11
