sample	coverage	taxonomy
2_component_58.1	10.24	Root; d__Viruses; p__Uroviricota; c__Caudoviricetes; o__novel_order_238_of_Caudoviricetes; f__novel_family_0_of_novel_order_238_of_Caudoviricetes; g__Dhillonvirus; s__Escherichia_phage_vB_EcoD_Pubbukkers
