sample	coverage	taxonomy
2_component_78.1	7.83	Root; d__Viruses; p__Uroviricota; c__Caudoviricetes; o__novel_order_23_of_Caudoviricetes; f__Kyanoviridae; g__novel_genus_0_of_novel_subfamily_0_of_Kyanoviridae; s__Synechococcus_phage_S-H34
