sample	coverage	taxonomy
2_component_59.1	8.94	Root; d__Viruses; p__Uroviricota; c__Caudoviricetes; o__novel_order_237_of_Caudoviricetes; f__novel_family_191_of_novel_order_237_of_Caudoviricetes; g__Roufvirus; s__Klebsiella_phage_VLCpiS13c
