sample	coverage	taxonomy
2_component_29.1	0.15	Root; d__Viruses; p__Uroviricota; c__Caudoviricetes; o__novel_order_237_of_Caudoviricetes; f__novel_family_191_of_novel_order_237_of_Caudoviricetes; g__Roufvirus
2_component_29.1	7.11	Root; d__Viruses; p__Uroviricota; c__Caudoviricetes; o__novel_order_237_of_Caudoviricetes; f__novel_family_191_of_novel_order_237_of_Caudoviricetes; g__Roufvirus; s__Klebsiella_phage_vB_Kpn_ZCKp20p
