sample	coverage	taxonomy
MH834621.1	8.43	Root; d__Viruses; p__Uroviricota; c__Caudoviricetes; o__novel_order_47_of_Caudoviricetes; f__novel_family_20_of_novel_order_47_of_Caudoviricetes; g__novel_genus_7_of_novel_subfamily_0_of_novel_family_20_of_novel_order_47_of_Caudoviricetes||novel_family_21_of_novel_order_47_of_Caudoviricetes; s__Arthrobacter_phage_Nandita
