sample	coverage	taxonomy
MN234184.1	5.29	Root; d__Viruses; p__Uroviricota; c__Caudoviricetes; o__novel_order_48_of_Caudoviricetes; f__novel_family_24_of_novel_order_48_of_Caudoviricetes; g__novel_genus_1_of_novel_subfamily_0_of_novel_family_24_of_novel_order_48_of_Caudoviricetes||novel_family_10_of_novel_order_46_of_Caudoviricetes; s__Mycobacterium_phage_IdentityCrisis
